name: chainkey_platform_interface
description: Common platform interface for the chainkey federated plugin.
version: 0.1.1
repository: https://github.com/GhagSagar23/chainkey/tree/master/packages/chainkey_platform_interface
issue_tracker: https://github.com/GhagSagar23/chainkey/issues
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
