// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Hardware security isolation tier backing the cryptographic key.
enum EnclaveIsolationLevel {
  /// Apple Secure Enclave (SEP) hardware isolated environment.
  secureEnclave,

  /// Android StrongBox Keymaster/KeyMint dedicated hardware security chip.
  strongBox,

  /// Android Trusted Execution Environment (TEE).
  tee,

  /// Software-backed or browser-managed key (e.g. software sandbox or WebAuthn).
  software;
}

/// Format of hardware attestation certificate chain or assertion statement.
enum KeyAttestationFormat {
  /// Android KeyStore X.509 attestation certificate chain (ASN.1 DER encoded).
  androidKeyStore,

  /// Apple DeviceCheck / AppAttest assertion and CBOR attestation object.
  appleAppAttest,

  /// No hardware attestation format available.
  none;
}

/// Parameters for generating a non-exportable NIST P-256 hardware key.
class HardwareKeyOptions {
  HardwareKeyOptions({
    required this.keyAlias,
    required this.requireUserPresence,
    required this.requireStrongBox,
    required this.invalidatedByBiometricEnrollment,
    this.accessGroup,
  });

  /// Unique alias/identifier for the hardware key.
  String keyAlias;

  /// Whether user presence (biometric or device passcode) is required to use the key.
  bool requireUserPresence;

  /// On Android, request a dedicated StrongBox HSM chip. If false or unavailable, falls back to TEE.
  bool requireStrongBox;

  /// On Android, controls whether adding a new biometric enrollment permanently invalidates the key.
  /// Recommended: false to prevent accidental user lockout.
  bool invalidatedByBiometricEnrollment;

  /// On iOS, optional Keychain Access Group for cross-app sharing.
  String? accessGroup;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      requireUserPresence,
      requireStrongBox,
      invalidatedByBiometricEnrollment,
      accessGroup,
    ];
  }

  Object encode() {
    return _toList();
  }

  static HardwareKeyOptions decode(Object result) {
    result as List<Object?>;
    return HardwareKeyOptions(
      keyAlias: result[0]! as String,
      requireUserPresence: result[1]! as bool,
      requireStrongBox: result[2]! as bool,
      invalidatedByBiometricEnrollment: result[3]! as bool,
      accessGroup: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HardwareKeyOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(requireUserPresence, other.requireUserPresence) &&
        _deepEquals(requireStrongBox, other.requireStrongBox) &&
        _deepEquals(invalidatedByBiometricEnrollment,
            other.invalidatedByBiometricEnrollment) &&
        _deepEquals(accessGroup, other.accessGroup);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'HardwareKeyOptions(keyAlias: $keyAlias, requireUserPresence: $requireUserPresence, requireStrongBox: $requireStrongBox, invalidatedByBiometricEnrollment: $invalidatedByBiometricEnrollment, accessGroup: $accessGroup)';
  }
}

/// Configuration options for native biometric prompt dialogs (Face ID / Touch ID / BiometricPrompt).
class PromptOptions {
  PromptOptions({
    required this.title,
    this.subtitle,
    this.promptDescription,
    required this.negativeButtonText,
    required this.confirmationRequired,
  });

  /// Title displayed on the biometric prompt.
  String title;

  /// Optional subtitle displayed on the biometric prompt.
  String? subtitle;

  /// Description explaining the transaction or UserOperation to sign.
  String? promptDescription;

  /// Label for the negative button (e.g. "Cancel").
  String negativeButtonText;

  /// On Android, whether explicit confirmation (tapping confirm button after sensor match) is required.
  bool confirmationRequired;

  List<Object?> _toList() {
    return <Object?>[
      title,
      subtitle,
      promptDescription,
      negativeButtonText,
      confirmationRequired,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PromptOptions decode(Object result) {
    result as List<Object?>;
    return PromptOptions(
      title: result[0]! as String,
      subtitle: result[1] as String?,
      promptDescription: result[2] as String?,
      negativeButtonText: result[3]! as String,
      confirmationRequired: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PromptOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(subtitle, other.subtitle) &&
        _deepEquals(promptDescription, other.promptDescription) &&
        _deepEquals(negativeButtonText, other.negativeButtonText) &&
        _deepEquals(confirmationRequired, other.confirmationRequired);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PromptOptions(title: $title, subtitle: $subtitle, promptDescription: $promptDescription, negativeButtonText: $negativeButtonText, confirmationRequired: $confirmationRequired)';
  }
}

/// A parsed NIST P-256 (secp256r1) public key representation.
class EnclavePublicKey {
  EnclavePublicKey({
    required this.keyAlias,
    required this.x,
    required this.y,
    required this.uncompressedBytes,
    required this.isolationLevel,
  });

  /// Unique alias/identifier for the hardware key.
  String keyAlias;

  /// 32-byte big-endian X coordinate on the NIST P-256 curve.
  Uint8List x;

  /// 32-byte big-endian Y coordinate on the NIST P-256 curve.
  Uint8List y;

  /// 65-byte uncompressed SEC1 point representation: `0x04 || X (32B) || Y (32B)`.
  Uint8List uncompressedBytes;

  /// Hardware isolation tier where the private key was generated.
  EnclaveIsolationLevel isolationLevel;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      x,
      y,
      uncompressedBytes,
      isolationLevel,
    ];
  }

  Object encode() {
    return _toList();
  }

  static EnclavePublicKey decode(Object result) {
    result as List<Object?>;
    return EnclavePublicKey(
      keyAlias: result[0]! as String,
      x: result[1]! as Uint8List,
      y: result[2]! as Uint8List,
      uncompressedBytes: result[3]! as Uint8List,
      isolationLevel: result[4]! as EnclaveIsolationLevel,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EnclavePublicKey || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(uncompressedBytes, other.uncompressedBytes) &&
        _deepEquals(isolationLevel, other.isolationLevel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EnclavePublicKey(keyAlias: $keyAlias, x: $x, y: $y, uncompressedBytes: $uncompressedBytes, isolationLevel: $isolationLevel)';
  }
}

/// ASN.1 DER signature result and pre-unpacked (r, s) scalar components.
class DerSignatureResult {
  DerSignatureResult({
    required this.keyAlias,
    required this.rawDerSignature,
    required this.r,
    required this.s,
    required this.isLowS,
  });

  /// Unique alias/identifier for the hardware key that signed the digest.
  String keyAlias;

  /// Raw ASN.1 DER encoded ECDSA signature from hardware:
  /// `0x30 || length || 0x02 || r_length || r || 0x02 || s_length || s`.
  Uint8List rawDerSignature;

  /// 32-byte big-endian `r` scalar (leading zero padding stripped, padded to 32 bytes).
  Uint8List r;

  /// 32-byte big-endian `s` scalar.
  Uint8List s;

  /// True if `s` is normalized to low-S ($s \le n/2$) per BIP-62 / EIP-2.
  bool isLowS;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      rawDerSignature,
      r,
      s,
      isLowS,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DerSignatureResult decode(Object result) {
    result as List<Object?>;
    return DerSignatureResult(
      keyAlias: result[0]! as String,
      rawDerSignature: result[1]! as Uint8List,
      r: result[2]! as Uint8List,
      s: result[3]! as Uint8List,
      isLowS: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DerSignatureResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(rawDerSignature, other.rawDerSignature) &&
        _deepEquals(r, other.r) &&
        _deepEquals(s, other.s) &&
        _deepEquals(isLowS, other.isLowS);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DerSignatureResult(keyAlias: $keyAlias, rawDerSignature: $rawDerSignature, r: $r, s: $s, isLowS: $isLowS)';
  }
}

/// Request parameters for creating a WebAuthn / Passkey credential.
class PasskeyCreationRequest {
  PasskeyCreationRequest({
    required this.relyingPartyId,
    required this.userName,
    required this.userDisplayName,
    required this.userId,
    required this.challenge,
    required this.requireUserVerification,
    this.origin,
  });

  /// Relying Party identifier (e.g. "wallet.example.com").
  String relyingPartyId;

  /// User account name (e.g. "user@example.com").
  String userName;

  /// Friendly display name for the user.
  String userDisplayName;

  /// Unique user entity identifier bytes.
  Uint8List userId;

  /// Cryptographic challenge bytes (e.g. 32-byte random challenge or UserOpHash).
  Uint8List challenge;

  /// Whether user verification (biometrics / PIN) is required ("required", "preferred", "discouraged").
  bool requireUserVerification;

  /// Optional origin URL (useful for Web/hybrid environments).
  String? origin;

  List<Object?> _toList() {
    return <Object?>[
      relyingPartyId,
      userName,
      userDisplayName,
      userId,
      challenge,
      requireUserVerification,
      origin,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PasskeyCreationRequest decode(Object result) {
    result as List<Object?>;
    return PasskeyCreationRequest(
      relyingPartyId: result[0]! as String,
      userName: result[1]! as String,
      userDisplayName: result[2]! as String,
      userId: result[3]! as Uint8List,
      challenge: result[4]! as Uint8List,
      requireUserVerification: result[5]! as bool,
      origin: result[6] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PasskeyCreationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(relyingPartyId, other.relyingPartyId) &&
        _deepEquals(userName, other.userName) &&
        _deepEquals(userDisplayName, other.userDisplayName) &&
        _deepEquals(userId, other.userId) &&
        _deepEquals(challenge, other.challenge) &&
        _deepEquals(requireUserVerification, other.requireUserVerification) &&
        _deepEquals(origin, other.origin);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PasskeyCreationRequest(relyingPartyId: $relyingPartyId, userName: $userName, userDisplayName: $userDisplayName, userId: $userId, challenge: $challenge, requireUserVerification: $requireUserVerification, origin: $origin)';
  }
}

/// WebAuthn / Passkey credential creation response.
class PasskeyCreationResponse {
  PasskeyCreationResponse({
    required this.credentialId,
    required this.rawAttestationObject,
    required this.rawClientDataJson,
    required this.publicKey,
    required this.isolationLevel,
  });

  /// Base64URL-encoded unique credential ID.
  String credentialId;

  /// Raw authenticator attestation object bytes.
  Uint8List rawAttestationObject;

  /// Raw UTF-8 bytes of clientDataJSON.
  Uint8List rawClientDataJson;

  /// Parsed NIST P-256 public key.
  EnclavePublicKey publicKey;

  /// Security isolation tier backing the credential.
  EnclaveIsolationLevel isolationLevel;

  List<Object?> _toList() {
    return <Object?>[
      credentialId,
      rawAttestationObject,
      rawClientDataJson,
      publicKey,
      isolationLevel,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PasskeyCreationResponse decode(Object result) {
    result as List<Object?>;
    return PasskeyCreationResponse(
      credentialId: result[0]! as String,
      rawAttestationObject: result[1]! as Uint8List,
      rawClientDataJson: result[2]! as Uint8List,
      publicKey: result[3]! as EnclavePublicKey,
      isolationLevel: result[4]! as EnclaveIsolationLevel,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PasskeyCreationResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(credentialId, other.credentialId) &&
        _deepEquals(rawAttestationObject, other.rawAttestationObject) &&
        _deepEquals(rawClientDataJson, other.rawClientDataJson) &&
        _deepEquals(publicKey, other.publicKey) &&
        _deepEquals(isolationLevel, other.isolationLevel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PasskeyCreationResponse(credentialId: $credentialId, rawAttestationObject: $rawAttestationObject, rawClientDataJson: $rawClientDataJson, publicKey: $publicKey, isolationLevel: $isolationLevel)';
  }
}

/// Request parameters for WebAuthn / Passkey assertion (authentication / signing).
class PasskeyAssertionRequest {
  PasskeyAssertionRequest({
    required this.relyingPartyId,
    required this.challenge,
    this.allowedCredentialIds,
    required this.requireUserVerification,
  });

  /// Relying Party identifier (e.g. "wallet.example.com").
  String relyingPartyId;

  /// Cryptographic challenge bytes (e.g. 32-byte UserOpHash).
  Uint8List challenge;

  /// Optional list of credential IDs allowed to assert.
  List<String>? allowedCredentialIds;

  /// Whether user verification (biometrics / PIN) is required.
  bool requireUserVerification;

  List<Object?> _toList() {
    return <Object?>[
      relyingPartyId,
      challenge,
      allowedCredentialIds,
      requireUserVerification,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PasskeyAssertionRequest decode(Object result) {
    result as List<Object?>;
    return PasskeyAssertionRequest(
      relyingPartyId: result[0]! as String,
      challenge: result[1]! as Uint8List,
      allowedCredentialIds: (result[2] as List<Object?>?)?.cast<String>(),
      requireUserVerification: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PasskeyAssertionRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(relyingPartyId, other.relyingPartyId) &&
        _deepEquals(challenge, other.challenge) &&
        _deepEquals(allowedCredentialIds, other.allowedCredentialIds) &&
        _deepEquals(requireUserVerification, other.requireUserVerification);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PasskeyAssertionRequest(relyingPartyId: $relyingPartyId, challenge: $challenge, allowedCredentialIds: $allowedCredentialIds, requireUserVerification: $requireUserVerification)';
  }
}

/// WebAuthn / Passkey assertion response.
class PasskeyAssertionResponse {
  PasskeyAssertionResponse({
    required this.credentialId,
    required this.authenticatorData,
    required this.clientDataJson,
    required this.signature,
    this.userHandle,
  });

  /// Base64URL-encoded credential ID that signed the assertion.
  String credentialId;

  /// Raw authenticator data bytes containing flags and counters.
  Uint8List authenticatorData;

  /// Raw UTF-8 bytes of clientDataJSON.
  Uint8List clientDataJson;

  /// ASN.1 DER signature along with pre-unpacked (r, s) scalars.
  DerSignatureResult signature;

  /// Optional user handle returned by authenticator.
  Uint8List? userHandle;

  List<Object?> _toList() {
    return <Object?>[
      credentialId,
      authenticatorData,
      clientDataJson,
      signature,
      userHandle,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PasskeyAssertionResponse decode(Object result) {
    result as List<Object?>;
    return PasskeyAssertionResponse(
      credentialId: result[0]! as String,
      authenticatorData: result[1]! as Uint8List,
      clientDataJson: result[2]! as Uint8List,
      signature: result[3]! as DerSignatureResult,
      userHandle: result[4] as Uint8List?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PasskeyAssertionResponse ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(credentialId, other.credentialId) &&
        _deepEquals(authenticatorData, other.authenticatorData) &&
        _deepEquals(clientDataJson, other.clientDataJson) &&
        _deepEquals(signature, other.signature) &&
        _deepEquals(userHandle, other.userHandle);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PasskeyAssertionResponse(credentialId: $credentialId, authenticatorData: $authenticatorData, clientDataJson: $clientDataJson, signature: $signature, userHandle: $userHandle)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is EnclaveIsolationLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is KeyAttestationFormat) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is HardwareKeyOptions) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PromptOptions) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is EnclavePublicKey) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is DerSignatureResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PasskeyCreationRequest) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PasskeyCreationResponse) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PasskeyAssertionRequest) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PasskeyAssertionResponse) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : EnclaveIsolationLevel.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : KeyAttestationFormat.values[value];
      case 131:
        return HardwareKeyOptions.decode(readValue(buffer)!);
      case 132:
        return PromptOptions.decode(readValue(buffer)!);
      case 133:
        return EnclavePublicKey.decode(readValue(buffer)!);
      case 134:
        return DerSignatureResult.decode(readValue(buffer)!);
      case 135:
        return PasskeyCreationRequest.decode(readValue(buffer)!);
      case 136:
        return PasskeyCreationResponse.decode(readValue(buffer)!);
      case 137:
        return PasskeyAssertionRequest.decode(readValue(buffer)!);
      case 138:
        return PasskeyAssertionResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API for direct hardware enclave operations (NIST P-256 keygen, raw hash signing, key deletion).
class HardwareEnclaveHostApi {
  /// Constructor for [HardwareEnclaveHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HardwareEnclaveHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  })  : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Generates a non-exportable NIST P-256 keypair inside the hardware security enclave
  /// (Secure Enclave on iOS, StrongBox/TEE on Android).
  Future<EnclavePublicKey> generateKey(HardwareKeyOptions options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.generateKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as EnclavePublicKey;
  }

  /// Signs a raw 32-byte digest (e.g. ERC-4337 UserOpHash) directly using the hardware key.
  /// Returns the raw ASN.1 DER signature along with pre-unpacked (r, s) scalars.
  Future<DerSignatureResult> signRawHash(
      String keyAlias, Uint8List hash32, PromptOptions prompt) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.signRawHash$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[keyAlias, hash32, prompt]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as DerSignatureResult;
  }

  /// Deletes the keypair identified by [keyAlias] from the hardware keystore.
  Future<bool> deleteKey(String keyAlias) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.deleteKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[keyAlias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Returns the hardware isolation level for an existing key identified by [keyAlias].
  Future<EnclaveIsolationLevel> getIsolationLevel(String keyAlias) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.getIsolationLevel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[keyAlias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as EnclaveIsolationLevel;
  }

  /// Checks whether a specific hardware isolation tier is available on the physical device.
  Future<bool> isHardwareIsolationSupported(EnclaveIsolationLevel level) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.isHardwareIsolationSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[level]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Retrieves the public key coordinates for an existing keypair by [keyAlias].
  Future<EnclavePublicKey> getPublicKey(String keyAlias) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.getPublicKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[keyAlias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as EnclavePublicKey;
  }

  /// Checks if a keypair exists for the specified [keyAlias].
  Future<bool> hasKey(String keyAlias) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.hasKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[keyAlias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}

/// Host API for W3C WebAuthn / Passkey operations (registration and assertion).
class WebAuthnHostApi {
  /// Constructor for [WebAuthnHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  WebAuthnHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  })  : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Registers a new Passkey credential via native Credential Manager / ASAuthorization.
  Future<PasskeyCreationResponse> registerPasskey(
      PasskeyCreationRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.WebAuthnHostApi.registerPasskey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PasskeyCreationResponse;
  }

  /// Asserts an existing Passkey credential to authenticate or sign a challenge.
  Future<PasskeyAssertionResponse> assertPasskey(
      PasskeyAssertionRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.WebAuthnHostApi.assertPasskey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as PasskeyAssertionResponse;
  }
}
