// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
  List<Object?>? replyList,
  String channelName, {
  required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

/// Hardware security isolation tier backing the cryptographic key.
enum EnclaveIsolationLevel {
  /// Apple Secure Enclave (SEP) hardware isolated environment.
  secureEnclave,

  /// Android StrongBox Keymaster/KeyMint dedicated hardware security chip.
  strongBox,

  /// Android Trusted Execution Environment (TEE).
  tee,

  /// Software-backed or browser-managed key (e.g. software sandbox or WebAuthn).
  software;
}

/// Format of hardware attestation certificate chain or assertion statement.
enum KeyAttestationFormat {
  /// Android KeyStore X.509 attestation certificate chain (ASN.1 DER encoded).
  androidKeyStore,

  /// Apple DeviceCheck / AppAttest assertion and CBOR attestation object.
  appleAppAttest,

  /// No hardware attestation format available.
  none;
}

/// Parameters for generating a non-exportable NIST P-256 keypair.
class KeyGenerationRequest {
  KeyGenerationRequest({
    required this.keyAlias,
    required this.requireUserPresence,
    required this.requireStrongBox,
    required this.invalidatedByBiometricEnrollment,
    this.accessGroup,
  });

  /// Unique alias/identifier for the hardware key.
  String keyAlias;

  /// Whether user presence (biometric or device passcode) is required to use the key.
  bool requireUserPresence;

  /// On Android, request a dedicated StrongBox HSM chip. If false or unavailable, falls back to TEE.
  bool requireStrongBox;

  /// On Android, controls whether adding a new fingerprint permanently invalidates the key.
  /// Recommended: false to prevent accidental user lockout.
  bool invalidatedByBiometricEnrollment;

  /// On iOS, optional Keychain Access Group for cross-app sharing.
  String? accessGroup;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      requireUserPresence,
      requireStrongBox,
      invalidatedByBiometricEnrollment,
      accessGroup,
    ];
  }

  Object encode() {
    return _toList();
  }

  static KeyGenerationRequest decode(Object result) {
    result as List<Object?>;
    return KeyGenerationRequest(
      keyAlias: result[0]! as String,
      requireUserPresence: result[1]! as bool,
      requireStrongBox: result[2]! as bool,
      invalidatedByBiometricEnrollment: result[3]! as bool,
      accessGroup: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! KeyGenerationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(requireUserPresence, other.requireUserPresence) &&
        _deepEquals(requireStrongBox, other.requireStrongBox) &&
        _deepEquals(invalidatedByBiometricEnrollment,
            other.invalidatedByBiometricEnrollment) &&
        _deepEquals(accessGroup, other.accessGroup);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'KeyGenerationRequest(keyAlias: $keyAlias, requireUserPresence: $requireUserPresence, requireStrongBox: $requireStrongBox, invalidatedByBiometricEnrollment: $invalidatedByBiometricEnrollment, accessGroup: $accessGroup)';
  }
}

/// A parsed NIST P-256 (secp256r1) public key representation.
class EnclavePublicKey {
  EnclavePublicKey({
    required this.keyAlias,
    required this.x,
    required this.y,
    required this.uncompressedBytes,
    required this.isolationLevel,
  });

  /// Unique alias/identifier for the hardware key.
  String keyAlias;

  /// 32-byte big-endian X coordinate on the NIST P-256 curve.
  Uint8List x;

  /// 32-byte big-endian Y coordinate on the NIST P-256 curve.
  Uint8List y;

  /// 65-byte uncompressed SEC1 point representation: `0x04 || X (32B) || Y (32B)`.
  Uint8List uncompressedBytes;

  /// Hardware isolation tier where the private key was generated.
  EnclaveIsolationLevel isolationLevel;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      x,
      y,
      uncompressedBytes,
      isolationLevel,
    ];
  }

  Object encode() {
    return _toList();
  }

  static EnclavePublicKey decode(Object result) {
    result as List<Object?>;
    return EnclavePublicKey(
      keyAlias: result[0]! as String,
      x: result[1]! as Uint8List,
      y: result[2]! as Uint8List,
      uncompressedBytes: result[3]! as Uint8List,
      isolationLevel: result[4]! as EnclaveIsolationLevel,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EnclavePublicKey || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(uncompressedBytes, other.uncompressedBytes) &&
        _deepEquals(isolationLevel, other.isolationLevel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EnclavePublicKey(keyAlias: $keyAlias, x: $x, y: $y, uncompressedBytes: $uncompressedBytes, isolationLevel: $isolationLevel)';
  }
}

/// Configuration options for native biometric prompt dialogs (Face ID / Touch ID / BiometricPrompt).
class PlatformPromptOptions {
  PlatformPromptOptions({
    required this.title,
    this.subtitle,
    this.promptDescription,
    required this.negativeButtonText,
    required this.confirmationRequired,
  });

  /// Title displayed on the biometric prompt.
  String title;

  /// Optional subtitle displayed on the biometric prompt.
  String? subtitle;

  /// Description explaining the transaction or UserOperation to sign.
  String? promptDescription;

  /// Label for the negative button (e.g. "Cancel").
  String negativeButtonText;

  /// On Android, whether explicit confirmation (tapping confirm button after sensor match) is required.
  bool confirmationRequired;

  List<Object?> _toList() {
    return <Object?>[
      title,
      subtitle,
      promptDescription,
      negativeButtonText,
      confirmationRequired,
    ];
  }

  Object encode() {
    return _toList();
  }

  static PlatformPromptOptions decode(Object result) {
    result as List<Object?>;
    return PlatformPromptOptions(
      title: result[0]! as String,
      subtitle: result[1] as String?,
      promptDescription: result[2] as String?,
      negativeButtonText: result[3]! as String,
      confirmationRequired: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PlatformPromptOptions || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(title, other.title) &&
        _deepEquals(subtitle, other.subtitle) &&
        _deepEquals(promptDescription, other.promptDescription) &&
        _deepEquals(negativeButtonText, other.negativeButtonText) &&
        _deepEquals(confirmationRequired, other.confirmationRequired);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PlatformPromptOptions(title: $title, subtitle: $subtitle, promptDescription: $promptDescription, negativeButtonText: $negativeButtonText, confirmationRequired: $confirmationRequired)';
  }
}

/// Request to sign a raw 32-byte digest (e.g. ERC-4337 UserOpHash) directly with a hardware key.
class SignDigestRequest {
  SignDigestRequest({
    required this.keyAlias,
    required this.hash32,
    this.promptOptions,
  });

  /// Unique alias/identifier for the hardware key.
  String keyAlias;

  /// Exact 32-byte digest to sign.
  Uint8List hash32;

  /// Optional native biometric prompt customization.
  PlatformPromptOptions? promptOptions;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      hash32,
      promptOptions,
    ];
  }

  Object encode() {
    return _toList();
  }

  static SignDigestRequest decode(Object result) {
    result as List<Object?>;
    return SignDigestRequest(
      keyAlias: result[0]! as String,
      hash32: result[1]! as Uint8List,
      promptOptions: result[2] as PlatformPromptOptions?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SignDigestRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(hash32, other.hash32) &&
        _deepEquals(promptOptions, other.promptOptions);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SignDigestRequest(keyAlias: $keyAlias, hash32: $hash32, promptOptions: $promptOptions)';
  }
}

/// ASN.1 DER signature result and pre-unpacked (r, s) scalar components.
class DerSignatureResult {
  DerSignatureResult({
    required this.keyAlias,
    required this.rawDerSignature,
    required this.r,
    required this.s,
    required this.isLowS,
  });

  /// Unique alias/identifier for the hardware key that signed the digest.
  String keyAlias;

  /// Raw ASN.1 DER encoded ECDSA signature from hardware:
  /// `0x30 || length || 0x02 || r_length || r || 0x02 || s_length || s`.
  Uint8List rawDerSignature;

  /// 32-byte big-endian `r` scalar (leading zero padding stripped, padded to 32 bytes).
  Uint8List r;

  /// 32-byte big-endian `s` scalar.
  Uint8List s;

  /// True if `s` is normalized to low-S ($s \le n/2$) per BIP-62 / EIP-2.
  bool isLowS;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      rawDerSignature,
      r,
      s,
      isLowS,
    ];
  }

  Object encode() {
    return _toList();
  }

  static DerSignatureResult decode(Object result) {
    result as List<Object?>;
    return DerSignatureResult(
      keyAlias: result[0]! as String,
      rawDerSignature: result[1]! as Uint8List,
      r: result[2]! as Uint8List,
      s: result[3]! as Uint8List,
      isLowS: result[4]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DerSignatureResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(rawDerSignature, other.rawDerSignature) &&
        _deepEquals(r, other.r) &&
        _deepEquals(s, other.s) &&
        _deepEquals(isLowS, other.isLowS);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DerSignatureResult(keyAlias: $keyAlias, rawDerSignature: $rawDerSignature, r: $r, s: $s, isLowS: $isLowS)';
  }
}

/// Request for cryptographic hardware attestation.
class AttestationRequest {
  AttestationRequest({
    required this.keyAlias,
    required this.challenge,
  });

  /// Unique alias/identifier for the hardware key to attest.
  String keyAlias;

  /// Server/contract provided challenge nonce to prevent replay attacks.
  Uint8List challenge;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      challenge,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AttestationRequest decode(Object result) {
    result as List<Object?>;
    return AttestationRequest(
      keyAlias: result[0]! as String,
      challenge: result[1]! as Uint8List,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttestationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(challenge, other.challenge);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AttestationRequest(keyAlias: $keyAlias, challenge: $challenge)';
  }
}

/// Hardware attestation verification payload.
class AttestationResult {
  AttestationResult({
    required this.keyAlias,
    required this.certificateChain,
    required this.format,
    required this.isolationLevel,
  });

  /// Unique alias/identifier for the attested key.
  String keyAlias;

  /// X.509 certificate chain in ASN.1 DER encoding (leaf certificate first).
  List<Uint8List> certificateChain;

  /// Attestation statement format.
  KeyAttestationFormat format;

  /// Hardware isolation tier confirmed by the hardware.
  EnclaveIsolationLevel isolationLevel;

  List<Object?> _toList() {
    return <Object?>[
      keyAlias,
      certificateChain,
      format,
      isolationLevel,
    ];
  }

  Object encode() {
    return _toList();
  }

  static AttestationResult decode(Object result) {
    result as List<Object?>;
    return AttestationResult(
      keyAlias: result[0]! as String,
      certificateChain: (result[1]! as List<Object?>).cast<Uint8List>(),
      format: result[2]! as KeyAttestationFormat,
      isolationLevel: result[3]! as EnclaveIsolationLevel,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AttestationResult || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(keyAlias, other.keyAlias) &&
        _deepEquals(certificateChain, other.certificateChain) &&
        _deepEquals(format, other.format) &&
        _deepEquals(isolationLevel, other.isolationLevel);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AttestationResult(keyAlias: $keyAlias, certificateChain: $certificateChain, format: $format, isolationLevel: $isolationLevel)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is EnclaveIsolationLevel) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is KeyAttestationFormat) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is KeyGenerationRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is EnclavePublicKey) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PlatformPromptOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is SignDigestRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is DerSignatureResult) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is AttestationRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is AttestationResult) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : EnclaveIsolationLevel.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : KeyAttestationFormat.values[value];
      case 131:
        return KeyGenerationRequest.decode(readValue(buffer)!);
      case 132:
        return EnclavePublicKey.decode(readValue(buffer)!);
      case 133:
        return PlatformPromptOptions.decode(readValue(buffer)!);
      case 134:
        return SignDigestRequest.decode(readValue(buffer)!);
      case 135:
        return DerSignatureResult.decode(readValue(buffer)!);
      case 136:
        return AttestationRequest.decode(readValue(buffer)!);
      case 137:
        return AttestationResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// Host API for direct hardware enclave operations (NIST P-256 keygen, attestation, and ASN.1 DER signing).
class HardwareKeyHostApi {
  /// Constructor for [HardwareKeyHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HardwareKeyHostApi({
    BinaryMessenger? binaryMessenger,
    String messageChannelSuffix = '',
  })  : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// Checks whether a specific hardware isolation tier is available on the physical device.
  Future<bool> isHardwareIsolationSupported(EnclaveIsolationLevel level) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.isHardwareIsolationSupported$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[level]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Generates a non-exportable NIST P-256 keypair inside the hardware security enclave
  /// (Secure Enclave on iOS, StrongBox/TEE on Android).
  Future<EnclavePublicKey> generateKeyPair(KeyGenerationRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.generateKeyPair$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as EnclavePublicKey;
  }

  /// Signs a raw 32-byte digest (e.g. ERC-4337 UserOpHash) directly using the hardware key.
  /// Returns the raw ASN.1 DER signature along with pre-unpacked (r, s) scalars.
  Future<DerSignatureResult> signDigest(SignDigestRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.signDigest$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as DerSignatureResult;
  }

  /// Requests hardware attestation for the key, embedding [request.challenge] into the certificate
  /// chain to verify hardware backing.
  Future<AttestationResult> attestKey(AttestationRequest request) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.attestKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as AttestationResult;
  }

  /// Retrieves the public key coordinates for an existing keypair by [keyAlias].
  Future<EnclavePublicKey> getPublicKey(String keyAlias) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.getPublicKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[keyAlias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as EnclavePublicKey;
  }

  /// Checks if a keypair exists for the specified [keyAlias].
  Future<bool> hasKey(String keyAlias) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.hasKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[keyAlias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }

  /// Deletes the keypair identified by [keyAlias] from the hardware keystore.
  Future<bool> deleteKey(String keyAlias) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.deleteKey$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[keyAlias]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as bool;
  }
}
