// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

enum ChainkeyApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Hardware security isolation tier backing the cryptographic key.
enum EnclaveIsolationLevel: Int, CaseIterable {
  /// Apple Secure Enclave (SEP) hardware isolated environment.
  case secureEnclave = 0
  /// Android StrongBox Keymaster/KeyMint dedicated hardware security chip.
  case strongBox = 1
  /// Android Trusted Execution Environment (TEE).
  case tee = 2
  /// Software-backed or browser-managed key (e.g. software sandbox or WebAuthn).
  case software = 3
}

/// Format of hardware attestation certificate chain or assertion statement.
enum KeyAttestationFormat: Int, CaseIterable {
  /// Android KeyStore X.509 attestation certificate chain (ASN.1 DER encoded).
  case androidKeyStore = 0
  /// Apple DeviceCheck / AppAttest assertion and CBOR attestation object.
  case appleAppAttest = 1
  /// No hardware attestation format available.
  case none = 2
}

/// Parameters for generating a non-exportable NIST P-256 hardware key.
///
/// Generated class from Pigeon that represents data sent in messages.
struct HardwareKeyOptions: Hashable, CustomStringConvertible {
  /// Unique alias/identifier for the hardware key.
  var keyAlias: String
  /// Whether user presence (biometric or device passcode) is required to use the key.
  var requireUserPresence: Bool
  /// On Android, request a dedicated StrongBox HSM chip. If false or unavailable, falls back to TEE.
  var requireStrongBox: Bool
  /// On Android, controls whether adding a new biometric enrollment permanently invalidates the key.
  /// Recommended: false to prevent accidental user lockout.
  var invalidatedByBiometricEnrollment: Bool
  /// On iOS, optional Keychain Access Group for cross-app sharing.
  var accessGroup: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HardwareKeyOptions? {
    let keyAlias = pigeonVar_list[0] as! String
    let requireUserPresence = pigeonVar_list[1] as! Bool
    let requireStrongBox = pigeonVar_list[2] as! Bool
    let invalidatedByBiometricEnrollment = pigeonVar_list[3] as! Bool
    let accessGroup: String? = nilOrValue(pigeonVar_list[4])

    return HardwareKeyOptions(
      keyAlias: keyAlias,
      requireUserPresence: requireUserPresence,
      requireStrongBox: requireStrongBox,
      invalidatedByBiometricEnrollment: invalidatedByBiometricEnrollment,
      accessGroup: accessGroup
    )
  }
  func toList() -> [Any?] {
    return [
      keyAlias,
      requireUserPresence,
      requireStrongBox,
      invalidatedByBiometricEnrollment,
      accessGroup,
    ]
  }
  static func == (lhs: HardwareKeyOptions, rhs: HardwareKeyOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ChainkeyApiPigeonInternal.deepEquals(lhs.keyAlias, rhs.keyAlias) && ChainkeyApiPigeonInternal.deepEquals(lhs.requireUserPresence, rhs.requireUserPresence) && ChainkeyApiPigeonInternal.deepEquals(lhs.requireStrongBox, rhs.requireStrongBox) && ChainkeyApiPigeonInternal.deepEquals(lhs.invalidatedByBiometricEnrollment, rhs.invalidatedByBiometricEnrollment) && ChainkeyApiPigeonInternal.deepEquals(lhs.accessGroup, rhs.accessGroup)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("HardwareKeyOptions")
    ChainkeyApiPigeonInternal.deepHash(value: keyAlias, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: requireUserPresence, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: requireStrongBox, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: invalidatedByBiometricEnrollment, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: accessGroup, hasher: &hasher)
  }

  public var description: String {
    return "HardwareKeyOptions(keyAlias: \(String(describing: keyAlias)), requireUserPresence: \(String(describing: requireUserPresence)), requireStrongBox: \(String(describing: requireStrongBox)), invalidatedByBiometricEnrollment: \(String(describing: invalidatedByBiometricEnrollment)), accessGroup: \(String(describing: accessGroup)))"
  }
}

/// Configuration options for native biometric prompt dialogs (Face ID / Touch ID / BiometricPrompt).
///
/// Generated class from Pigeon that represents data sent in messages.
struct PromptOptions: Hashable, CustomStringConvertible {
  /// Title displayed on the biometric prompt.
  var title: String
  /// Optional subtitle displayed on the biometric prompt.
  var subtitle: String? = nil
  /// Description explaining the transaction or UserOperation to sign.
  var promptDescription: String? = nil
  /// Label for the negative button (e.g. "Cancel").
  var negativeButtonText: String
  /// On Android, whether explicit confirmation (tapping confirm button after sensor match) is required.
  var confirmationRequired: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PromptOptions? {
    let title = pigeonVar_list[0] as! String
    let subtitle: String? = nilOrValue(pigeonVar_list[1])
    let promptDescription: String? = nilOrValue(pigeonVar_list[2])
    let negativeButtonText = pigeonVar_list[3] as! String
    let confirmationRequired = pigeonVar_list[4] as! Bool

    return PromptOptions(
      title: title,
      subtitle: subtitle,
      promptDescription: promptDescription,
      negativeButtonText: negativeButtonText,
      confirmationRequired: confirmationRequired
    )
  }
  func toList() -> [Any?] {
    return [
      title,
      subtitle,
      promptDescription,
      negativeButtonText,
      confirmationRequired,
    ]
  }
  static func == (lhs: PromptOptions, rhs: PromptOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ChainkeyApiPigeonInternal.deepEquals(lhs.title, rhs.title) && ChainkeyApiPigeonInternal.deepEquals(lhs.subtitle, rhs.subtitle) && ChainkeyApiPigeonInternal.deepEquals(lhs.promptDescription, rhs.promptDescription) && ChainkeyApiPigeonInternal.deepEquals(lhs.negativeButtonText, rhs.negativeButtonText) && ChainkeyApiPigeonInternal.deepEquals(lhs.confirmationRequired, rhs.confirmationRequired)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PromptOptions")
    ChainkeyApiPigeonInternal.deepHash(value: title, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: subtitle, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: promptDescription, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: negativeButtonText, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: confirmationRequired, hasher: &hasher)
  }

  public var description: String {
    return "PromptOptions(title: \(String(describing: title)), subtitle: \(String(describing: subtitle)), promptDescription: \(String(describing: promptDescription)), negativeButtonText: \(String(describing: negativeButtonText)), confirmationRequired: \(String(describing: confirmationRequired)))"
  }
}

/// A parsed NIST P-256 (secp256r1) public key representation.
///
/// Generated class from Pigeon that represents data sent in messages.
struct EnclavePublicKey: Hashable, CustomStringConvertible {
  /// Unique alias/identifier for the hardware key.
  var keyAlias: String
  /// 32-byte big-endian X coordinate on the NIST P-256 curve.
  var x: FlutterStandardTypedData
  /// 32-byte big-endian Y coordinate on the NIST P-256 curve.
  var y: FlutterStandardTypedData
  /// 65-byte uncompressed SEC1 point representation: `0x04 || X (32B) || Y (32B)`.
  var uncompressedBytes: FlutterStandardTypedData
  /// Hardware isolation tier where the private key was generated.
  var isolationLevel: EnclaveIsolationLevel


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EnclavePublicKey? {
    let keyAlias = pigeonVar_list[0] as! String
    let x = pigeonVar_list[1] as! FlutterStandardTypedData
    let y = pigeonVar_list[2] as! FlutterStandardTypedData
    let uncompressedBytes = pigeonVar_list[3] as! FlutterStandardTypedData
    let isolationLevel = pigeonVar_list[4] as! EnclaveIsolationLevel

    return EnclavePublicKey(
      keyAlias: keyAlias,
      x: x,
      y: y,
      uncompressedBytes: uncompressedBytes,
      isolationLevel: isolationLevel
    )
  }
  func toList() -> [Any?] {
    return [
      keyAlias,
      x,
      y,
      uncompressedBytes,
      isolationLevel,
    ]
  }
  static func == (lhs: EnclavePublicKey, rhs: EnclavePublicKey) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ChainkeyApiPigeonInternal.deepEquals(lhs.keyAlias, rhs.keyAlias) && ChainkeyApiPigeonInternal.deepEquals(lhs.x, rhs.x) && ChainkeyApiPigeonInternal.deepEquals(lhs.y, rhs.y) && ChainkeyApiPigeonInternal.deepEquals(lhs.uncompressedBytes, rhs.uncompressedBytes) && ChainkeyApiPigeonInternal.deepEquals(lhs.isolationLevel, rhs.isolationLevel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EnclavePublicKey")
    ChainkeyApiPigeonInternal.deepHash(value: keyAlias, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: x, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: y, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: uncompressedBytes, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: isolationLevel, hasher: &hasher)
  }

  public var description: String {
    return "EnclavePublicKey(keyAlias: \(String(describing: keyAlias)), x: \(String(describing: x)), y: \(String(describing: y)), uncompressedBytes: \(String(describing: uncompressedBytes)), isolationLevel: \(String(describing: isolationLevel)))"
  }
}

/// ASN.1 DER signature result and pre-unpacked (r, s) scalar components.
///
/// Generated class from Pigeon that represents data sent in messages.
struct DerSignatureResult: Hashable, CustomStringConvertible {
  /// Unique alias/identifier for the hardware key that signed the digest.
  var keyAlias: String
  /// Raw ASN.1 DER encoded ECDSA signature from hardware:
  /// `0x30 || length || 0x02 || r_length || r || 0x02 || s_length || s`.
  var rawDerSignature: FlutterStandardTypedData
  /// 32-byte big-endian `r` scalar (leading zero padding stripped, padded to 32 bytes).
  var r: FlutterStandardTypedData
  /// 32-byte big-endian `s` scalar.
  var s: FlutterStandardTypedData
  /// True if `s` is normalized to low-S ($s \le n/2$) per BIP-62 / EIP-2.
  var isLowS: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DerSignatureResult? {
    let keyAlias = pigeonVar_list[0] as! String
    let rawDerSignature = pigeonVar_list[1] as! FlutterStandardTypedData
    let r = pigeonVar_list[2] as! FlutterStandardTypedData
    let s = pigeonVar_list[3] as! FlutterStandardTypedData
    let isLowS = pigeonVar_list[4] as! Bool

    return DerSignatureResult(
      keyAlias: keyAlias,
      rawDerSignature: rawDerSignature,
      r: r,
      s: s,
      isLowS: isLowS
    )
  }
  func toList() -> [Any?] {
    return [
      keyAlias,
      rawDerSignature,
      r,
      s,
      isLowS,
    ]
  }
  static func == (lhs: DerSignatureResult, rhs: DerSignatureResult) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ChainkeyApiPigeonInternal.deepEquals(lhs.keyAlias, rhs.keyAlias) && ChainkeyApiPigeonInternal.deepEquals(lhs.rawDerSignature, rhs.rawDerSignature) && ChainkeyApiPigeonInternal.deepEquals(lhs.r, rhs.r) && ChainkeyApiPigeonInternal.deepEquals(lhs.s, rhs.s) && ChainkeyApiPigeonInternal.deepEquals(lhs.isLowS, rhs.isLowS)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DerSignatureResult")
    ChainkeyApiPigeonInternal.deepHash(value: keyAlias, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: rawDerSignature, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: r, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: s, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: isLowS, hasher: &hasher)
  }

  public var description: String {
    return "DerSignatureResult(keyAlias: \(String(describing: keyAlias)), rawDerSignature: \(String(describing: rawDerSignature)), r: \(String(describing: r)), s: \(String(describing: s)), isLowS: \(String(describing: isLowS)))"
  }
}

/// Request parameters for creating a WebAuthn / Passkey credential.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PasskeyCreationRequest: Hashable, CustomStringConvertible {
  /// Relying Party identifier (e.g. "wallet.example.com").
  var relyingPartyId: String
  /// User account name (e.g. "user@example.com").
  var userName: String
  /// Friendly display name for the user.
  var userDisplayName: String
  /// Unique user entity identifier bytes.
  var userId: FlutterStandardTypedData
  /// Cryptographic challenge bytes (e.g. 32-byte random challenge or UserOpHash).
  var challenge: FlutterStandardTypedData
  /// Whether user verification (biometrics / PIN) is required ("required", "preferred", "discouraged").
  var requireUserVerification: Bool
  /// Optional origin URL (useful for Web/hybrid environments).
  var origin: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PasskeyCreationRequest? {
    let relyingPartyId = pigeonVar_list[0] as! String
    let userName = pigeonVar_list[1] as! String
    let userDisplayName = pigeonVar_list[2] as! String
    let userId = pigeonVar_list[3] as! FlutterStandardTypedData
    let challenge = pigeonVar_list[4] as! FlutterStandardTypedData
    let requireUserVerification = pigeonVar_list[5] as! Bool
    let origin: String? = nilOrValue(pigeonVar_list[6])

    return PasskeyCreationRequest(
      relyingPartyId: relyingPartyId,
      userName: userName,
      userDisplayName: userDisplayName,
      userId: userId,
      challenge: challenge,
      requireUserVerification: requireUserVerification,
      origin: origin
    )
  }
  func toList() -> [Any?] {
    return [
      relyingPartyId,
      userName,
      userDisplayName,
      userId,
      challenge,
      requireUserVerification,
      origin,
    ]
  }
  static func == (lhs: PasskeyCreationRequest, rhs: PasskeyCreationRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ChainkeyApiPigeonInternal.deepEquals(lhs.relyingPartyId, rhs.relyingPartyId) && ChainkeyApiPigeonInternal.deepEquals(lhs.userName, rhs.userName) && ChainkeyApiPigeonInternal.deepEquals(lhs.userDisplayName, rhs.userDisplayName) && ChainkeyApiPigeonInternal.deepEquals(lhs.userId, rhs.userId) && ChainkeyApiPigeonInternal.deepEquals(lhs.challenge, rhs.challenge) && ChainkeyApiPigeonInternal.deepEquals(lhs.requireUserVerification, rhs.requireUserVerification) && ChainkeyApiPigeonInternal.deepEquals(lhs.origin, rhs.origin)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PasskeyCreationRequest")
    ChainkeyApiPigeonInternal.deepHash(value: relyingPartyId, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: userName, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: userDisplayName, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: userId, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: challenge, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: requireUserVerification, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: origin, hasher: &hasher)
  }

  public var description: String {
    return "PasskeyCreationRequest(relyingPartyId: \(String(describing: relyingPartyId)), userName: \(String(describing: userName)), userDisplayName: \(String(describing: userDisplayName)), userId: \(String(describing: userId)), challenge: \(String(describing: challenge)), requireUserVerification: \(String(describing: requireUserVerification)), origin: \(String(describing: origin)))"
  }
}

/// WebAuthn / Passkey credential creation response.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PasskeyCreationResponse: Hashable, CustomStringConvertible {
  /// Base64URL-encoded unique credential ID.
  var credentialId: String
  /// Raw authenticator attestation object bytes.
  var rawAttestationObject: FlutterStandardTypedData
  /// Raw UTF-8 bytes of clientDataJSON.
  var rawClientDataJson: FlutterStandardTypedData
  /// Parsed NIST P-256 public key.
  var publicKey: EnclavePublicKey
  /// Security isolation tier backing the credential.
  var isolationLevel: EnclaveIsolationLevel


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PasskeyCreationResponse? {
    let credentialId = pigeonVar_list[0] as! String
    let rawAttestationObject = pigeonVar_list[1] as! FlutterStandardTypedData
    let rawClientDataJson = pigeonVar_list[2] as! FlutterStandardTypedData
    let publicKey = pigeonVar_list[3] as! EnclavePublicKey
    let isolationLevel = pigeonVar_list[4] as! EnclaveIsolationLevel

    return PasskeyCreationResponse(
      credentialId: credentialId,
      rawAttestationObject: rawAttestationObject,
      rawClientDataJson: rawClientDataJson,
      publicKey: publicKey,
      isolationLevel: isolationLevel
    )
  }
  func toList() -> [Any?] {
    return [
      credentialId,
      rawAttestationObject,
      rawClientDataJson,
      publicKey,
      isolationLevel,
    ]
  }
  static func == (lhs: PasskeyCreationResponse, rhs: PasskeyCreationResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ChainkeyApiPigeonInternal.deepEquals(lhs.credentialId, rhs.credentialId) && ChainkeyApiPigeonInternal.deepEquals(lhs.rawAttestationObject, rhs.rawAttestationObject) && ChainkeyApiPigeonInternal.deepEquals(lhs.rawClientDataJson, rhs.rawClientDataJson) && ChainkeyApiPigeonInternal.deepEquals(lhs.publicKey, rhs.publicKey) && ChainkeyApiPigeonInternal.deepEquals(lhs.isolationLevel, rhs.isolationLevel)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PasskeyCreationResponse")
    ChainkeyApiPigeonInternal.deepHash(value: credentialId, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: rawAttestationObject, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: rawClientDataJson, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: publicKey, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: isolationLevel, hasher: &hasher)
  }

  public var description: String {
    return "PasskeyCreationResponse(credentialId: \(String(describing: credentialId)), rawAttestationObject: \(String(describing: rawAttestationObject)), rawClientDataJson: \(String(describing: rawClientDataJson)), publicKey: \(String(describing: publicKey)), isolationLevel: \(String(describing: isolationLevel)))"
  }
}

/// Request parameters for WebAuthn / Passkey assertion (authentication / signing).
///
/// Generated class from Pigeon that represents data sent in messages.
struct PasskeyAssertionRequest: Hashable, CustomStringConvertible {
  /// Relying Party identifier (e.g. "wallet.example.com").
  var relyingPartyId: String
  /// Cryptographic challenge bytes (e.g. 32-byte UserOpHash).
  var challenge: FlutterStandardTypedData
  /// Optional list of credential IDs allowed to assert.
  var allowedCredentialIds: [String]? = nil
  /// Whether user verification (biometrics / PIN) is required.
  var requireUserVerification: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PasskeyAssertionRequest? {
    let relyingPartyId = pigeonVar_list[0] as! String
    let challenge = pigeonVar_list[1] as! FlutterStandardTypedData
    let allowedCredentialIds: [String]? = nilOrValue(pigeonVar_list[2])
    let requireUserVerification = pigeonVar_list[3] as! Bool

    return PasskeyAssertionRequest(
      relyingPartyId: relyingPartyId,
      challenge: challenge,
      allowedCredentialIds: allowedCredentialIds,
      requireUserVerification: requireUserVerification
    )
  }
  func toList() -> [Any?] {
    return [
      relyingPartyId,
      challenge,
      allowedCredentialIds,
      requireUserVerification,
    ]
  }
  static func == (lhs: PasskeyAssertionRequest, rhs: PasskeyAssertionRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ChainkeyApiPigeonInternal.deepEquals(lhs.relyingPartyId, rhs.relyingPartyId) && ChainkeyApiPigeonInternal.deepEquals(lhs.challenge, rhs.challenge) && ChainkeyApiPigeonInternal.deepEquals(lhs.allowedCredentialIds, rhs.allowedCredentialIds) && ChainkeyApiPigeonInternal.deepEquals(lhs.requireUserVerification, rhs.requireUserVerification)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PasskeyAssertionRequest")
    ChainkeyApiPigeonInternal.deepHash(value: relyingPartyId, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: challenge, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: allowedCredentialIds, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: requireUserVerification, hasher: &hasher)
  }

  public var description: String {
    return "PasskeyAssertionRequest(relyingPartyId: \(String(describing: relyingPartyId)), challenge: \(String(describing: challenge)), allowedCredentialIds: \(String(describing: allowedCredentialIds)), requireUserVerification: \(String(describing: requireUserVerification)))"
  }
}

/// WebAuthn / Passkey assertion response.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PasskeyAssertionResponse: Hashable, CustomStringConvertible {
  /// Base64URL-encoded credential ID that signed the assertion.
  var credentialId: String
  /// Raw authenticator data bytes containing flags and counters.
  var authenticatorData: FlutterStandardTypedData
  /// Raw UTF-8 bytes of clientDataJSON.
  var clientDataJson: FlutterStandardTypedData
  /// ASN.1 DER signature along with pre-unpacked (r, s) scalars.
  var signature: DerSignatureResult
  /// Optional user handle returned by authenticator.
  var userHandle: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PasskeyAssertionResponse? {
    let credentialId = pigeonVar_list[0] as! String
    let authenticatorData = pigeonVar_list[1] as! FlutterStandardTypedData
    let clientDataJson = pigeonVar_list[2] as! FlutterStandardTypedData
    let signature = pigeonVar_list[3] as! DerSignatureResult
    let userHandle: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[4])

    return PasskeyAssertionResponse(
      credentialId: credentialId,
      authenticatorData: authenticatorData,
      clientDataJson: clientDataJson,
      signature: signature,
      userHandle: userHandle
    )
  }
  func toList() -> [Any?] {
    return [
      credentialId,
      authenticatorData,
      clientDataJson,
      signature,
      userHandle,
    ]
  }
  static func == (lhs: PasskeyAssertionResponse, rhs: PasskeyAssertionResponse) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ChainkeyApiPigeonInternal.deepEquals(lhs.credentialId, rhs.credentialId) && ChainkeyApiPigeonInternal.deepEquals(lhs.authenticatorData, rhs.authenticatorData) && ChainkeyApiPigeonInternal.deepEquals(lhs.clientDataJson, rhs.clientDataJson) && ChainkeyApiPigeonInternal.deepEquals(lhs.signature, rhs.signature) && ChainkeyApiPigeonInternal.deepEquals(lhs.userHandle, rhs.userHandle)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PasskeyAssertionResponse")
    ChainkeyApiPigeonInternal.deepHash(value: credentialId, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: authenticatorData, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: clientDataJson, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: signature, hasher: &hasher)
    ChainkeyApiPigeonInternal.deepHash(value: userHandle, hasher: &hasher)
  }

  public var description: String {
    return "PasskeyAssertionResponse(credentialId: \(String(describing: credentialId)), authenticatorData: \(String(describing: authenticatorData)), clientDataJson: \(String(describing: clientDataJson)), signature: \(String(describing: signature)), userHandle: \(String(describing: userHandle)))"
  }
}

private class ChainkeyApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EnclaveIsolationLevel(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return KeyAttestationFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return HardwareKeyOptions.fromList(self.readValue() as! [Any?])
    case 132:
      return PromptOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return EnclavePublicKey.fromList(self.readValue() as! [Any?])
    case 134:
      return DerSignatureResult.fromList(self.readValue() as! [Any?])
    case 135:
      return PasskeyCreationRequest.fromList(self.readValue() as! [Any?])
    case 136:
      return PasskeyCreationResponse.fromList(self.readValue() as! [Any?])
    case 137:
      return PasskeyAssertionRequest.fromList(self.readValue() as! [Any?])
    case 138:
      return PasskeyAssertionResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ChainkeyApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? EnclaveIsolationLevel {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? KeyAttestationFormat {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? HardwareKeyOptions {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PromptOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? EnclavePublicKey {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? DerSignatureResult {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PasskeyCreationRequest {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PasskeyCreationResponse {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PasskeyAssertionRequest {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PasskeyAssertionResponse {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ChainkeyApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ChainkeyApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ChainkeyApiPigeonCodecWriter(data: data)
  }
}

class ChainkeyApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ChainkeyApiPigeonCodec(readerWriter: ChainkeyApiPigeonCodecReaderWriter())
}


/// Host API for direct hardware enclave operations (NIST P-256 keygen, raw hash signing, key deletion).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HardwareEnclaveHostApi {
  /// Generates a non-exportable NIST P-256 keypair inside the hardware security enclave
  /// (Secure Enclave on iOS, StrongBox/TEE on Android).
  func generateKey(options: HardwareKeyOptions) async throws -> EnclavePublicKey
  /// Signs a raw 32-byte digest (e.g. ERC-4337 UserOpHash) directly using the hardware key.
  /// Returns the raw ASN.1 DER signature along with pre-unpacked (r, s) scalars.
  func signRawHash(keyAlias: String, hash32: FlutterStandardTypedData, prompt: PromptOptions) async throws -> DerSignatureResult
  /// Deletes the keypair identified by [keyAlias] from the hardware keystore.
  func deleteKey(keyAlias: String) throws -> Bool
  /// Returns the hardware isolation level for an existing key identified by [keyAlias].
  func getIsolationLevel(keyAlias: String) throws -> EnclaveIsolationLevel
  /// Checks whether a specific hardware isolation tier is available on the physical device.
  func isHardwareIsolationSupported(level: EnclaveIsolationLevel) throws -> Bool
  /// Retrieves the public key coordinates for an existing keypair by [keyAlias].
  func getPublicKey(keyAlias: String) throws -> EnclavePublicKey
  /// Checks if a keypair exists for the specified [keyAlias].
  func hasKey(keyAlias: String) throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HardwareEnclaveHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ChainkeyApiPigeonCodec.shared }
  /// Sets up an instance of `HardwareEnclaveHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HardwareEnclaveHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Generates a non-exportable NIST P-256 keypair inside the hardware security enclave
    /// (Secure Enclave on iOS, StrongBox/TEE on Android).
    let generateKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.generateKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let optionsArg = args[0] as! HardwareKeyOptions
        Task { @MainActor in
          do {
            let result = try await api.generateKey(options: optionsArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      generateKeyChannel.setMessageHandler(nil)
    }
    /// Signs a raw 32-byte digest (e.g. ERC-4337 UserOpHash) directly using the hardware key.
    /// Returns the raw ASN.1 DER signature along with pre-unpacked (r, s) scalars.
    let signRawHashChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.signRawHash\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signRawHashChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg = args[0] as! String
        let hash32Arg = args[1] as! FlutterStandardTypedData
        let promptArg = args[2] as! PromptOptions
        Task { @MainActor in
          do {
            let result = try await api.signRawHash(keyAlias: keyAliasArg, hash32: hash32Arg, prompt: promptArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      signRawHashChannel.setMessageHandler(nil)
    }
    /// Deletes the keypair identified by [keyAlias] from the hardware keystore.
    let deleteKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.deleteKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg = args[0] as! String
        do {
          let result = try api.deleteKey(keyAlias: keyAliasArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      deleteKeyChannel.setMessageHandler(nil)
    }
    /// Returns the hardware isolation level for an existing key identified by [keyAlias].
    let getIsolationLevelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.getIsolationLevel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getIsolationLevelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg = args[0] as! String
        do {
          let result = try api.getIsolationLevel(keyAlias: keyAliasArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getIsolationLevelChannel.setMessageHandler(nil)
    }
    /// Checks whether a specific hardware isolation tier is available on the physical device.
    let isHardwareIsolationSupportedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.isHardwareIsolationSupported\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isHardwareIsolationSupportedChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let levelArg = args[0] as! EnclaveIsolationLevel
        do {
          let result = try api.isHardwareIsolationSupported(level: levelArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isHardwareIsolationSupportedChannel.setMessageHandler(nil)
    }
    /// Retrieves the public key coordinates for an existing keypair by [keyAlias].
    let getPublicKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.getPublicKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPublicKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg = args[0] as! String
        do {
          let result = try api.getPublicKey(keyAlias: keyAliasArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getPublicKeyChannel.setMessageHandler(nil)
    }
    /// Checks if a keypair exists for the specified [keyAlias].
    let hasKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.hasKey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      hasKeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyAliasArg = args[0] as! String
        do {
          let result = try api.hasKey(keyAlias: keyAliasArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      hasKeyChannel.setMessageHandler(nil)
    }
  }
}
/// Host API for W3C WebAuthn / Passkey operations (registration and assertion).
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol WebAuthnHostApi {
  /// Registers a new Passkey credential via native Credential Manager / ASAuthorization.
  func registerPasskey(request: PasskeyCreationRequest) async throws -> PasskeyCreationResponse
  /// Asserts an existing Passkey credential to authenticate or sign a challenge.
  func assertPasskey(request: PasskeyAssertionRequest) async throws -> PasskeyAssertionResponse
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class WebAuthnHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ChainkeyApiPigeonCodec.shared }
  /// Sets up an instance of `WebAuthnHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: WebAuthnHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Registers a new Passkey credential via native Credential Manager / ASAuthorization.
    let registerPasskeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.WebAuthnHostApi.registerPasskey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      registerPasskeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PasskeyCreationRequest
        Task { @MainActor in
          do {
            let result = try await api.registerPasskey(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      registerPasskeyChannel.setMessageHandler(nil)
    }
    /// Asserts an existing Passkey credential to authenticate or sign a challenge.
    let assertPasskeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.chainkey_platform_interface.WebAuthnHostApi.assertPasskey\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      assertPasskeyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PasskeyAssertionRequest
        Task { @MainActor in
          do {
            let result = try await api.assertPasskey(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      assertPasskeyChannel.setMessageHandler(nil)
    }
  }
}
