name: chainkey_example
description: Demonstrates how to use the chainkey plugin.
publish_to: 'none'
resolution: workspace

environment:
  sdk: ^3.5.0
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  chainkey:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
