// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.chainkey.chainkey_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object ChainkeyApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Hardware security isolation tier backing the cryptographic key. */
enum class EnclaveIsolationLevel(val raw: Int) {
  /** Apple Secure Enclave (SEP) hardware isolated environment. */
  SECURE_ENCLAVE(0),
  /** Android StrongBox Keymaster/KeyMint dedicated hardware security chip. */
  STRONG_BOX(1),
  /** Android Trusted Execution Environment (TEE). */
  TEE(2),
  /** Software-backed or browser-managed key (e.g. software sandbox or WebAuthn). */
  SOFTWARE(3);

  companion object {
    fun ofRaw(raw: Int): EnclaveIsolationLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Format of hardware attestation certificate chain or assertion statement. */
enum class KeyAttestationFormat(val raw: Int) {
  /** Android KeyStore X.509 attestation certificate chain (ASN.1 DER encoded). */
  ANDROID_KEY_STORE(0),
  /** Apple DeviceCheck / AppAttest assertion and CBOR attestation object. */
  APPLE_APP_ATTEST(1),
  /** No hardware attestation format available. */
  NONE(2);

  companion object {
    fun ofRaw(raw: Int): KeyAttestationFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Parameters for generating a non-exportable NIST P-256 hardware key.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class HardwareKeyOptions (
  /** Unique alias/identifier for the hardware key. */
  val keyAlias: String,
  /** Whether user presence (biometric or device passcode) is required to use the key. */
  val requireUserPresence: Boolean,
  /** On Android, request a dedicated StrongBox HSM chip. If false or unavailable, falls back to TEE. */
  val requireStrongBox: Boolean,
  /**
   * On Android, controls whether adding a new biometric enrollment permanently invalidates the key.
   * Recommended: false to prevent accidental user lockout.
   */
  val invalidatedByBiometricEnrollment: Boolean,
  /** On iOS, optional Keychain Access Group for cross-app sharing. */
  val accessGroup: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HardwareKeyOptions {
      val keyAlias = pigeonVar_list[0] as String
      val requireUserPresence = pigeonVar_list[1] as Boolean
      val requireStrongBox = pigeonVar_list[2] as Boolean
      val invalidatedByBiometricEnrollment = pigeonVar_list[3] as Boolean
      val accessGroup = pigeonVar_list[4] as String?
      return HardwareKeyOptions(keyAlias, requireUserPresence, requireStrongBox, invalidatedByBiometricEnrollment, accessGroup)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      requireUserPresence,
      requireStrongBox,
      invalidatedByBiometricEnrollment,
      accessGroup,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as HardwareKeyOptions
    return ChainkeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && ChainkeyApiPigeonUtils.deepEquals(this.requireUserPresence, other.requireUserPresence) && ChainkeyApiPigeonUtils.deepEquals(this.requireStrongBox, other.requireStrongBox) && ChainkeyApiPigeonUtils.deepEquals(this.invalidatedByBiometricEnrollment, other.invalidatedByBiometricEnrollment) && ChainkeyApiPigeonUtils.deepEquals(this.accessGroup, other.accessGroup)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.requireUserPresence)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.requireStrongBox)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.invalidatedByBiometricEnrollment)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.accessGroup)
    return result
  }
  override fun toString(): String {
    return "HardwareKeyOptions(keyAlias=$keyAlias, requireUserPresence=$requireUserPresence, requireStrongBox=$requireStrongBox, invalidatedByBiometricEnrollment=$invalidatedByBiometricEnrollment, accessGroup=$accessGroup)"
  }
}

/**
 * Configuration options for native biometric prompt dialogs (Face ID / Touch ID / BiometricPrompt).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PromptOptions (
  /** Title displayed on the biometric prompt. */
  val title: String,
  /** Optional subtitle displayed on the biometric prompt. */
  val subtitle: String? = null,
  /** Description explaining the transaction or UserOperation to sign. */
  val promptDescription: String? = null,
  /** Label for the negative button (e.g. "Cancel"). */
  val negativeButtonText: String,
  /** On Android, whether explicit confirmation (tapping confirm button after sensor match) is required. */
  val confirmationRequired: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PromptOptions {
      val title = pigeonVar_list[0] as String
      val subtitle = pigeonVar_list[1] as String?
      val promptDescription = pigeonVar_list[2] as String?
      val negativeButtonText = pigeonVar_list[3] as String
      val confirmationRequired = pigeonVar_list[4] as Boolean
      return PromptOptions(title, subtitle, promptDescription, negativeButtonText, confirmationRequired)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      subtitle,
      promptDescription,
      negativeButtonText,
      confirmationRequired,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PromptOptions
    return ChainkeyApiPigeonUtils.deepEquals(this.title, other.title) && ChainkeyApiPigeonUtils.deepEquals(this.subtitle, other.subtitle) && ChainkeyApiPigeonUtils.deepEquals(this.promptDescription, other.promptDescription) && ChainkeyApiPigeonUtils.deepEquals(this.negativeButtonText, other.negativeButtonText) && ChainkeyApiPigeonUtils.deepEquals(this.confirmationRequired, other.confirmationRequired)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.title)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.subtitle)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.promptDescription)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.negativeButtonText)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.confirmationRequired)
    return result
  }
  override fun toString(): String {
    return "PromptOptions(title=$title, subtitle=$subtitle, promptDescription=$promptDescription, negativeButtonText=$negativeButtonText, confirmationRequired=$confirmationRequired)"
  }
}

/**
 * A parsed NIST P-256 (secp256r1) public key representation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EnclavePublicKey (
  /** Unique alias/identifier for the hardware key. */
  val keyAlias: String,
  /** 32-byte big-endian X coordinate on the NIST P-256 curve. */
  val x: ByteArray,
  /** 32-byte big-endian Y coordinate on the NIST P-256 curve. */
  val y: ByteArray,
  /** 65-byte uncompressed SEC1 point representation: `0x04 || X (32B) || Y (32B)`. */
  val uncompressedBytes: ByteArray,
  /** Hardware isolation tier where the private key was generated. */
  val isolationLevel: EnclaveIsolationLevel
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EnclavePublicKey {
      val keyAlias = pigeonVar_list[0] as String
      val x = pigeonVar_list[1] as ByteArray
      val y = pigeonVar_list[2] as ByteArray
      val uncompressedBytes = pigeonVar_list[3] as ByteArray
      val isolationLevel = pigeonVar_list[4] as EnclaveIsolationLevel
      return EnclavePublicKey(keyAlias, x, y, uncompressedBytes, isolationLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      x,
      y,
      uncompressedBytes,
      isolationLevel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EnclavePublicKey
    return ChainkeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && ChainkeyApiPigeonUtils.deepEquals(this.x, other.x) && ChainkeyApiPigeonUtils.deepEquals(this.y, other.y) && ChainkeyApiPigeonUtils.deepEquals(this.uncompressedBytes, other.uncompressedBytes) && ChainkeyApiPigeonUtils.deepEquals(this.isolationLevel, other.isolationLevel)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.x)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.y)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.uncompressedBytes)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.isolationLevel)
    return result
  }
  override fun toString(): String {
    return "EnclavePublicKey(keyAlias=$keyAlias, x=${x.contentToString()}, y=${y.contentToString()}, uncompressedBytes=${uncompressedBytes.contentToString()}, isolationLevel=$isolationLevel)"
  }
}

/**
 * ASN.1 DER signature result and pre-unpacked (r, s) scalar components.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DerSignatureResult (
  /** Unique alias/identifier for the hardware key that signed the digest. */
  val keyAlias: String,
  /**
   * Raw ASN.1 DER encoded ECDSA signature from hardware:
   * `0x30 || length || 0x02 || r_length || r || 0x02 || s_length || s`.
   */
  val rawDerSignature: ByteArray,
  /** 32-byte big-endian `r` scalar (leading zero padding stripped, padded to 32 bytes). */
  val r: ByteArray,
  /** 32-byte big-endian `s` scalar. */
  val s: ByteArray,
  /** True if `s` is normalized to low-S ($s \le n/2$) per BIP-62 / EIP-2. */
  val isLowS: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DerSignatureResult {
      val keyAlias = pigeonVar_list[0] as String
      val rawDerSignature = pigeonVar_list[1] as ByteArray
      val r = pigeonVar_list[2] as ByteArray
      val s = pigeonVar_list[3] as ByteArray
      val isLowS = pigeonVar_list[4] as Boolean
      return DerSignatureResult(keyAlias, rawDerSignature, r, s, isLowS)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      rawDerSignature,
      r,
      s,
      isLowS,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DerSignatureResult
    return ChainkeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && ChainkeyApiPigeonUtils.deepEquals(this.rawDerSignature, other.rawDerSignature) && ChainkeyApiPigeonUtils.deepEquals(this.r, other.r) && ChainkeyApiPigeonUtils.deepEquals(this.s, other.s) && ChainkeyApiPigeonUtils.deepEquals(this.isLowS, other.isLowS)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.rawDerSignature)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.r)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.s)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.isLowS)
    return result
  }
  override fun toString(): String {
    return "DerSignatureResult(keyAlias=$keyAlias, rawDerSignature=${rawDerSignature.contentToString()}, r=${r.contentToString()}, s=${s.contentToString()}, isLowS=$isLowS)"
  }
}

/**
 * Request parameters for creating a WebAuthn / Passkey credential.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PasskeyCreationRequest (
  /** Relying Party identifier (e.g. "wallet.example.com"). */
  val relyingPartyId: String,
  /** User account name (e.g. "user@example.com"). */
  val userName: String,
  /** Friendly display name for the user. */
  val userDisplayName: String,
  /** Unique user entity identifier bytes. */
  val userId: ByteArray,
  /** Cryptographic challenge bytes (e.g. 32-byte random challenge or UserOpHash). */
  val challenge: ByteArray,
  /** Whether user verification (biometrics / PIN) is required ("required", "preferred", "discouraged"). */
  val requireUserVerification: Boolean,
  /** Optional origin URL (useful for Web/hybrid environments). */
  val origin: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PasskeyCreationRequest {
      val relyingPartyId = pigeonVar_list[0] as String
      val userName = pigeonVar_list[1] as String
      val userDisplayName = pigeonVar_list[2] as String
      val userId = pigeonVar_list[3] as ByteArray
      val challenge = pigeonVar_list[4] as ByteArray
      val requireUserVerification = pigeonVar_list[5] as Boolean
      val origin = pigeonVar_list[6] as String?
      return PasskeyCreationRequest(relyingPartyId, userName, userDisplayName, userId, challenge, requireUserVerification, origin)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      relyingPartyId,
      userName,
      userDisplayName,
      userId,
      challenge,
      requireUserVerification,
      origin,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PasskeyCreationRequest
    return ChainkeyApiPigeonUtils.deepEquals(this.relyingPartyId, other.relyingPartyId) && ChainkeyApiPigeonUtils.deepEquals(this.userName, other.userName) && ChainkeyApiPigeonUtils.deepEquals(this.userDisplayName, other.userDisplayName) && ChainkeyApiPigeonUtils.deepEquals(this.userId, other.userId) && ChainkeyApiPigeonUtils.deepEquals(this.challenge, other.challenge) && ChainkeyApiPigeonUtils.deepEquals(this.requireUserVerification, other.requireUserVerification) && ChainkeyApiPigeonUtils.deepEquals(this.origin, other.origin)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.relyingPartyId)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.userName)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.userDisplayName)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.userId)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.challenge)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.requireUserVerification)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.origin)
    return result
  }
  override fun toString(): String {
    return "PasskeyCreationRequest(relyingPartyId=$relyingPartyId, userName=$userName, userDisplayName=$userDisplayName, userId=${userId.contentToString()}, challenge=${challenge.contentToString()}, requireUserVerification=$requireUserVerification, origin=$origin)"
  }
}

/**
 * WebAuthn / Passkey credential creation response.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PasskeyCreationResponse (
  /** Base64URL-encoded unique credential ID. */
  val credentialId: String,
  /** Raw authenticator attestation object bytes. */
  val rawAttestationObject: ByteArray,
  /** Raw UTF-8 bytes of clientDataJSON. */
  val rawClientDataJson: ByteArray,
  /** Parsed NIST P-256 public key. */
  val publicKey: EnclavePublicKey,
  /** Security isolation tier backing the credential. */
  val isolationLevel: EnclaveIsolationLevel
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PasskeyCreationResponse {
      val credentialId = pigeonVar_list[0] as String
      val rawAttestationObject = pigeonVar_list[1] as ByteArray
      val rawClientDataJson = pigeonVar_list[2] as ByteArray
      val publicKey = pigeonVar_list[3] as EnclavePublicKey
      val isolationLevel = pigeonVar_list[4] as EnclaveIsolationLevel
      return PasskeyCreationResponse(credentialId, rawAttestationObject, rawClientDataJson, publicKey, isolationLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      credentialId,
      rawAttestationObject,
      rawClientDataJson,
      publicKey,
      isolationLevel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PasskeyCreationResponse
    return ChainkeyApiPigeonUtils.deepEquals(this.credentialId, other.credentialId) && ChainkeyApiPigeonUtils.deepEquals(this.rawAttestationObject, other.rawAttestationObject) && ChainkeyApiPigeonUtils.deepEquals(this.rawClientDataJson, other.rawClientDataJson) && ChainkeyApiPigeonUtils.deepEquals(this.publicKey, other.publicKey) && ChainkeyApiPigeonUtils.deepEquals(this.isolationLevel, other.isolationLevel)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.credentialId)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.rawAttestationObject)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.rawClientDataJson)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.publicKey)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.isolationLevel)
    return result
  }
  override fun toString(): String {
    return "PasskeyCreationResponse(credentialId=$credentialId, rawAttestationObject=${rawAttestationObject.contentToString()}, rawClientDataJson=${rawClientDataJson.contentToString()}, publicKey=$publicKey, isolationLevel=$isolationLevel)"
  }
}

/**
 * Request parameters for WebAuthn / Passkey assertion (authentication / signing).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PasskeyAssertionRequest (
  /** Relying Party identifier (e.g. "wallet.example.com"). */
  val relyingPartyId: String,
  /** Cryptographic challenge bytes (e.g. 32-byte UserOpHash). */
  val challenge: ByteArray,
  /** Optional list of credential IDs allowed to assert. */
  val allowedCredentialIds: List<String>? = null,
  /** Whether user verification (biometrics / PIN) is required. */
  val requireUserVerification: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PasskeyAssertionRequest {
      val relyingPartyId = pigeonVar_list[0] as String
      val challenge = pigeonVar_list[1] as ByteArray
      val allowedCredentialIds = pigeonVar_list[2] as List<String>?
      val requireUserVerification = pigeonVar_list[3] as Boolean
      return PasskeyAssertionRequest(relyingPartyId, challenge, allowedCredentialIds, requireUserVerification)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      relyingPartyId,
      challenge,
      allowedCredentialIds,
      requireUserVerification,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PasskeyAssertionRequest
    return ChainkeyApiPigeonUtils.deepEquals(this.relyingPartyId, other.relyingPartyId) && ChainkeyApiPigeonUtils.deepEquals(this.challenge, other.challenge) && ChainkeyApiPigeonUtils.deepEquals(this.allowedCredentialIds, other.allowedCredentialIds) && ChainkeyApiPigeonUtils.deepEquals(this.requireUserVerification, other.requireUserVerification)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.relyingPartyId)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.challenge)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.allowedCredentialIds)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.requireUserVerification)
    return result
  }
  override fun toString(): String {
    return "PasskeyAssertionRequest(relyingPartyId=$relyingPartyId, challenge=${challenge.contentToString()}, allowedCredentialIds=$allowedCredentialIds, requireUserVerification=$requireUserVerification)"
  }
}

/**
 * WebAuthn / Passkey assertion response.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PasskeyAssertionResponse (
  /** Base64URL-encoded credential ID that signed the assertion. */
  val credentialId: String,
  /** Raw authenticator data bytes containing flags and counters. */
  val authenticatorData: ByteArray,
  /** Raw UTF-8 bytes of clientDataJSON. */
  val clientDataJson: ByteArray,
  /** ASN.1 DER signature along with pre-unpacked (r, s) scalars. */
  val signature: DerSignatureResult,
  /** Optional user handle returned by authenticator. */
  val userHandle: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PasskeyAssertionResponse {
      val credentialId = pigeonVar_list[0] as String
      val authenticatorData = pigeonVar_list[1] as ByteArray
      val clientDataJson = pigeonVar_list[2] as ByteArray
      val signature = pigeonVar_list[3] as DerSignatureResult
      val userHandle = pigeonVar_list[4] as ByteArray?
      return PasskeyAssertionResponse(credentialId, authenticatorData, clientDataJson, signature, userHandle)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      credentialId,
      authenticatorData,
      clientDataJson,
      signature,
      userHandle,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PasskeyAssertionResponse
    return ChainkeyApiPigeonUtils.deepEquals(this.credentialId, other.credentialId) && ChainkeyApiPigeonUtils.deepEquals(this.authenticatorData, other.authenticatorData) && ChainkeyApiPigeonUtils.deepEquals(this.clientDataJson, other.clientDataJson) && ChainkeyApiPigeonUtils.deepEquals(this.signature, other.signature) && ChainkeyApiPigeonUtils.deepEquals(this.userHandle, other.userHandle)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.credentialId)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.authenticatorData)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.clientDataJson)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.signature)
    result = 31 * result + ChainkeyApiPigeonUtils.deepHash(this.userHandle)
    return result
  }
  override fun toString(): String {
    return "PasskeyAssertionResponse(credentialId=$credentialId, authenticatorData=${authenticatorData.contentToString()}, clientDataJson=${clientDataJson.contentToString()}, signature=$signature, userHandle=${userHandle?.contentToString()})"
  }
}
private open class ChainkeyApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EnclaveIsolationLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KeyAttestationFormat.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HardwareKeyOptions.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PromptOptions.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EnclavePublicKey.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DerSignatureResult.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PasskeyCreationRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PasskeyCreationResponse.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PasskeyAssertionRequest.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PasskeyAssertionResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EnclaveIsolationLevel -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is KeyAttestationFormat -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is HardwareKeyOptions -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PromptOptions -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is EnclavePublicKey -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is DerSignatureResult -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PasskeyCreationRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PasskeyCreationResponse -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PasskeyAssertionRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PasskeyAssertionResponse -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for direct hardware enclave operations (NIST P-256 keygen, raw hash signing, key deletion).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HardwareEnclaveHostApi {
  /**
   * Generates a non-exportable NIST P-256 keypair inside the hardware security enclave
   * (Secure Enclave on iOS, StrongBox/TEE on Android).
   */
  suspend fun generateKey(options: HardwareKeyOptions): EnclavePublicKey
  /**
   * Signs a raw 32-byte digest (e.g. ERC-4337 UserOpHash) directly using the hardware key.
   * Returns the raw ASN.1 DER signature along with pre-unpacked (r, s) scalars.
   */
  suspend fun signRawHash(keyAlias: String, hash32: ByteArray, prompt: PromptOptions): DerSignatureResult
  /** Deletes the keypair identified by [keyAlias] from the hardware keystore. */
  fun deleteKey(keyAlias: String): Boolean
  /** Returns the hardware isolation level for an existing key identified by [keyAlias]. */
  fun getIsolationLevel(keyAlias: String): EnclaveIsolationLevel
  /** Checks whether a specific hardware isolation tier is available on the physical device. */
  fun isHardwareIsolationSupported(level: EnclaveIsolationLevel): Boolean
  /** Retrieves the public key coordinates for an existing keypair by [keyAlias]. */
  fun getPublicKey(keyAlias: String): EnclavePublicKey
  /** Checks if a keypair exists for the specified [keyAlias]. */
  fun hasKey(keyAlias: String): Boolean

  companion object {
    /** The codec used by HardwareEnclaveHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ChainkeyApiPigeonCodec()
    }
    /** Sets up an instance of `HardwareEnclaveHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HardwareEnclaveHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.generateKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as HardwareKeyOptions
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.generateKey(optionsArg))
              } catch (exception: Throwable) {
                ChainkeyApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.signRawHash$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String
            val hash32Arg = args[1] as ByteArray
            val promptArg = args[2] as PromptOptions
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.signRawHash(keyAliasArg, hash32Arg, promptArg))
              } catch (exception: Throwable) {
                ChainkeyApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.deleteKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.deleteKey(keyAliasArg))
            } catch (exception: Throwable) {
              ChainkeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.getIsolationLevel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getIsolationLevel(keyAliasArg))
            } catch (exception: Throwable) {
              ChainkeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.isHardwareIsolationSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as EnclaveIsolationLevel
            val wrapped: List<Any?> = try {
              listOf(api.isHardwareIsolationSupported(levelArg))
            } catch (exception: Throwable) {
              ChainkeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.getPublicKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getPublicKey(keyAliasArg))
            } catch (exception: Throwable) {
              ChainkeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareEnclaveHostApi.hasKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.hasKey(keyAliasArg))
            } catch (exception: Throwable) {
              ChainkeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/**
 * Host API for W3C WebAuthn / Passkey operations (registration and assertion).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface WebAuthnHostApi {
  /** Registers a new Passkey credential via native Credential Manager / ASAuthorization. */
  suspend fun registerPasskey(request: PasskeyCreationRequest): PasskeyCreationResponse
  /** Asserts an existing Passkey credential to authenticate or sign a challenge. */
  suspend fun assertPasskey(request: PasskeyAssertionRequest): PasskeyAssertionResponse

  companion object {
    /** The codec used by WebAuthnHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ChainkeyApiPigeonCodec()
    }
    /** Sets up an instance of `WebAuthnHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: WebAuthnHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.WebAuthnHostApi.registerPasskey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PasskeyCreationRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.registerPasskey(requestArg))
              } catch (exception: Throwable) {
                ChainkeyApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.WebAuthnHostApi.assertPasskey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PasskeyAssertionRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.assertPasskey(requestArg))
              } catch (exception: Throwable) {
                ChainkeyApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
