// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package dev.chainkey.chainkey_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object KeyApiPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Hardware security isolation tier backing the cryptographic key. */
enum class EnclaveIsolationLevel(val raw: Int) {
  /** Apple Secure Enclave (SEP) hardware isolated environment. */
  SECURE_ENCLAVE(0),
  /** Android StrongBox Keymaster/KeyMint dedicated hardware security chip. */
  STRONG_BOX(1),
  /** Android Trusted Execution Environment (TEE). */
  TEE(2),
  /** Software-backed or browser-managed key (e.g. software sandbox or WebAuthn). */
  SOFTWARE(3);

  companion object {
    fun ofRaw(raw: Int): EnclaveIsolationLevel? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Format of hardware attestation certificate chain or assertion statement. */
enum class KeyAttestationFormat(val raw: Int) {
  /** Android KeyStore X.509 attestation certificate chain (ASN.1 DER encoded). */
  ANDROID_KEY_STORE(0),
  /** Apple DeviceCheck / AppAttest assertion and CBOR attestation object. */
  APPLE_APP_ATTEST(1),
  /** No hardware attestation format available. */
  NONE(2);

  companion object {
    fun ofRaw(raw: Int): KeyAttestationFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * Parameters for generating a non-exportable NIST P-256 keypair.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class KeyGenerationRequest (
  /** Unique alias/identifier for the hardware key. */
  val keyAlias: String,
  /** Whether user presence (biometric or device passcode) is required to use the key. */
  val requireUserPresence: Boolean,
  /** On Android, request a dedicated StrongBox HSM chip. If false or unavailable, falls back to TEE. */
  val requireStrongBox: Boolean,
  /**
   * On Android, controls whether adding a new fingerprint permanently invalidates the key.
   * Recommended: false to prevent accidental user lockout.
   */
  val invalidatedByBiometricEnrollment: Boolean,
  /** On iOS, optional Keychain Access Group for cross-app sharing. */
  val accessGroup: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): KeyGenerationRequest {
      val keyAlias = pigeonVar_list[0] as String
      val requireUserPresence = pigeonVar_list[1] as Boolean
      val requireStrongBox = pigeonVar_list[2] as Boolean
      val invalidatedByBiometricEnrollment = pigeonVar_list[3] as Boolean
      val accessGroup = pigeonVar_list[4] as String?
      return KeyGenerationRequest(keyAlias, requireUserPresence, requireStrongBox, invalidatedByBiometricEnrollment, accessGroup)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      requireUserPresence,
      requireStrongBox,
      invalidatedByBiometricEnrollment,
      accessGroup,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as KeyGenerationRequest
    return KeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && KeyApiPigeonUtils.deepEquals(this.requireUserPresence, other.requireUserPresence) && KeyApiPigeonUtils.deepEquals(this.requireStrongBox, other.requireStrongBox) && KeyApiPigeonUtils.deepEquals(this.invalidatedByBiometricEnrollment, other.invalidatedByBiometricEnrollment) && KeyApiPigeonUtils.deepEquals(this.accessGroup, other.accessGroup)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.requireUserPresence)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.requireStrongBox)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.invalidatedByBiometricEnrollment)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.accessGroup)
    return result
  }
  override fun toString(): String {
    return "KeyGenerationRequest(keyAlias=$keyAlias, requireUserPresence=$requireUserPresence, requireStrongBox=$requireStrongBox, invalidatedByBiometricEnrollment=$invalidatedByBiometricEnrollment, accessGroup=$accessGroup)"
  }
}

/**
 * A parsed NIST P-256 (secp256r1) public key representation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EnclavePublicKey (
  /** Unique alias/identifier for the hardware key. */
  val keyAlias: String,
  /** 32-byte big-endian X coordinate on the NIST P-256 curve. */
  val x: ByteArray,
  /** 32-byte big-endian Y coordinate on the NIST P-256 curve. */
  val y: ByteArray,
  /** 65-byte uncompressed SEC1 point representation: `0x04 || X (32B) || Y (32B)`. */
  val uncompressedBytes: ByteArray,
  /** Hardware isolation tier where the private key was generated. */
  val isolationLevel: EnclaveIsolationLevel
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EnclavePublicKey {
      val keyAlias = pigeonVar_list[0] as String
      val x = pigeonVar_list[1] as ByteArray
      val y = pigeonVar_list[2] as ByteArray
      val uncompressedBytes = pigeonVar_list[3] as ByteArray
      val isolationLevel = pigeonVar_list[4] as EnclaveIsolationLevel
      return EnclavePublicKey(keyAlias, x, y, uncompressedBytes, isolationLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      x,
      y,
      uncompressedBytes,
      isolationLevel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EnclavePublicKey
    return KeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && KeyApiPigeonUtils.deepEquals(this.x, other.x) && KeyApiPigeonUtils.deepEquals(this.y, other.y) && KeyApiPigeonUtils.deepEquals(this.uncompressedBytes, other.uncompressedBytes) && KeyApiPigeonUtils.deepEquals(this.isolationLevel, other.isolationLevel)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.x)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.y)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.uncompressedBytes)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.isolationLevel)
    return result
  }
  override fun toString(): String {
    return "EnclavePublicKey(keyAlias=$keyAlias, x=${x.contentToString()}, y=${y.contentToString()}, uncompressedBytes=${uncompressedBytes.contentToString()}, isolationLevel=$isolationLevel)"
  }
}

/**
 * Configuration options for native biometric prompt dialogs (Face ID / Touch ID / BiometricPrompt).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class PlatformPromptOptions (
  /** Title displayed on the biometric prompt. */
  val title: String,
  /** Optional subtitle displayed on the biometric prompt. */
  val subtitle: String? = null,
  /** Description explaining the transaction or UserOperation to sign. */
  val promptDescription: String? = null,
  /** Label for the negative button (e.g. "Cancel"). */
  val negativeButtonText: String,
  /** On Android, whether explicit confirmation (tapping confirm button after sensor match) is required. */
  val confirmationRequired: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PlatformPromptOptions {
      val title = pigeonVar_list[0] as String
      val subtitle = pigeonVar_list[1] as String?
      val promptDescription = pigeonVar_list[2] as String?
      val negativeButtonText = pigeonVar_list[3] as String
      val confirmationRequired = pigeonVar_list[4] as Boolean
      return PlatformPromptOptions(title, subtitle, promptDescription, negativeButtonText, confirmationRequired)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      title,
      subtitle,
      promptDescription,
      negativeButtonText,
      confirmationRequired,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PlatformPromptOptions
    return KeyApiPigeonUtils.deepEquals(this.title, other.title) && KeyApiPigeonUtils.deepEquals(this.subtitle, other.subtitle) && KeyApiPigeonUtils.deepEquals(this.promptDescription, other.promptDescription) && KeyApiPigeonUtils.deepEquals(this.negativeButtonText, other.negativeButtonText) && KeyApiPigeonUtils.deepEquals(this.confirmationRequired, other.confirmationRequired)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.title)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.subtitle)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.promptDescription)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.negativeButtonText)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.confirmationRequired)
    return result
  }
  override fun toString(): String {
    return "PlatformPromptOptions(title=$title, subtitle=$subtitle, promptDescription=$promptDescription, negativeButtonText=$negativeButtonText, confirmationRequired=$confirmationRequired)"
  }
}

/**
 * Request to sign a raw 32-byte digest (e.g. ERC-4337 UserOpHash) directly with a hardware key.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class SignDigestRequest (
  /** Unique alias/identifier for the hardware key. */
  val keyAlias: String,
  /** Exact 32-byte digest to sign. */
  val hash32: ByteArray,
  /** Optional native biometric prompt customization. */
  val promptOptions: PlatformPromptOptions? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SignDigestRequest {
      val keyAlias = pigeonVar_list[0] as String
      val hash32 = pigeonVar_list[1] as ByteArray
      val promptOptions = pigeonVar_list[2] as PlatformPromptOptions?
      return SignDigestRequest(keyAlias, hash32, promptOptions)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      hash32,
      promptOptions,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SignDigestRequest
    return KeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && KeyApiPigeonUtils.deepEquals(this.hash32, other.hash32) && KeyApiPigeonUtils.deepEquals(this.promptOptions, other.promptOptions)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.hash32)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.promptOptions)
    return result
  }
  override fun toString(): String {
    return "SignDigestRequest(keyAlias=$keyAlias, hash32=${hash32.contentToString()}, promptOptions=$promptOptions)"
  }
}

/**
 * ASN.1 DER signature result and pre-unpacked (r, s) scalar components.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DerSignatureResult (
  /** Unique alias/identifier for the hardware key that signed the digest. */
  val keyAlias: String,
  /**
   * Raw ASN.1 DER encoded ECDSA signature from hardware:
   * `0x30 || length || 0x02 || r_length || r || 0x02 || s_length || s`.
   */
  val rawDerSignature: ByteArray,
  /** 32-byte big-endian `r` scalar (leading zero padding stripped, padded to 32 bytes). */
  val r: ByteArray,
  /** 32-byte big-endian `s` scalar. */
  val s: ByteArray,
  /** True if `s` is normalized to low-S ($s \le n/2$) per BIP-62 / EIP-2. */
  val isLowS: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DerSignatureResult {
      val keyAlias = pigeonVar_list[0] as String
      val rawDerSignature = pigeonVar_list[1] as ByteArray
      val r = pigeonVar_list[2] as ByteArray
      val s = pigeonVar_list[3] as ByteArray
      val isLowS = pigeonVar_list[4] as Boolean
      return DerSignatureResult(keyAlias, rawDerSignature, r, s, isLowS)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      rawDerSignature,
      r,
      s,
      isLowS,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DerSignatureResult
    return KeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && KeyApiPigeonUtils.deepEquals(this.rawDerSignature, other.rawDerSignature) && KeyApiPigeonUtils.deepEquals(this.r, other.r) && KeyApiPigeonUtils.deepEquals(this.s, other.s) && KeyApiPigeonUtils.deepEquals(this.isLowS, other.isLowS)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.rawDerSignature)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.r)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.s)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.isLowS)
    return result
  }
  override fun toString(): String {
    return "DerSignatureResult(keyAlias=$keyAlias, rawDerSignature=${rawDerSignature.contentToString()}, r=${r.contentToString()}, s=${s.contentToString()}, isLowS=$isLowS)"
  }
}

/**
 * Request for cryptographic hardware attestation.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AttestationRequest (
  /** Unique alias/identifier for the hardware key to attest. */
  val keyAlias: String,
  /** Server/contract provided challenge nonce to prevent replay attacks. */
  val challenge: ByteArray
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttestationRequest {
      val keyAlias = pigeonVar_list[0] as String
      val challenge = pigeonVar_list[1] as ByteArray
      return AttestationRequest(keyAlias, challenge)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      challenge,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttestationRequest
    return KeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && KeyApiPigeonUtils.deepEquals(this.challenge, other.challenge)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.challenge)
    return result
  }
  override fun toString(): String {
    return "AttestationRequest(keyAlias=$keyAlias, challenge=${challenge.contentToString()})"
  }
}

/**
 * Hardware attestation verification payload.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AttestationResult (
  /** Unique alias/identifier for the attested key. */
  val keyAlias: String,
  /** X.509 certificate chain in ASN.1 DER encoding (leaf certificate first). */
  val certificateChain: List<ByteArray>,
  /** Attestation statement format. */
  val format: KeyAttestationFormat,
  /** Hardware isolation tier confirmed by the hardware. */
  val isolationLevel: EnclaveIsolationLevel
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AttestationResult {
      val keyAlias = pigeonVar_list[0] as String
      val certificateChain = pigeonVar_list[1] as List<ByteArray>
      val format = pigeonVar_list[2] as KeyAttestationFormat
      val isolationLevel = pigeonVar_list[3] as EnclaveIsolationLevel
      return AttestationResult(keyAlias, certificateChain, format, isolationLevel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      keyAlias,
      certificateChain,
      format,
      isolationLevel,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AttestationResult
    return KeyApiPigeonUtils.deepEquals(this.keyAlias, other.keyAlias) && KeyApiPigeonUtils.deepEquals(this.certificateChain, other.certificateChain) && KeyApiPigeonUtils.deepEquals(this.format, other.format) && KeyApiPigeonUtils.deepEquals(this.isolationLevel, other.isolationLevel)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.keyAlias)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.certificateChain)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.format)
    result = 31 * result + KeyApiPigeonUtils.deepHash(this.isolationLevel)
    return result
  }
  override fun toString(): String {
    return "AttestationResult(keyAlias=$keyAlias, certificateChain=$certificateChain, format=$format, isolationLevel=$isolationLevel)"
  }
}
private open class KeyApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          EnclaveIsolationLevel.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          KeyAttestationFormat.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          KeyGenerationRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EnclavePublicKey.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PlatformPromptOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SignDigestRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DerSignatureResult.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttestationRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AttestationResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EnclaveIsolationLevel -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is KeyAttestationFormat -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is KeyGenerationRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is EnclavePublicKey -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PlatformPromptOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is SignDigestRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is DerSignatureResult -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is AttestationRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is AttestationResult -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/**
 * Host API for direct hardware enclave operations (NIST P-256 keygen, attestation, and ASN.1 DER signing).
 *
 * Generated interface from Pigeon that represents a handler of messages from Flutter.
 */
interface HardwareKeyHostApi {
  /** Checks whether a specific hardware isolation tier is available on the physical device. */
  fun isHardwareIsolationSupported(level: EnclaveIsolationLevel): Boolean
  /**
   * Generates a non-exportable NIST P-256 keypair inside the hardware security enclave
   * (Secure Enclave on iOS, StrongBox/TEE on Android).
   */
  suspend fun generateKeyPair(request: KeyGenerationRequest): EnclavePublicKey
  /**
   * Signs a raw 32-byte digest (e.g. ERC-4337 UserOpHash) directly using the hardware key.
   * Returns the raw ASN.1 DER signature along with pre-unpacked (r, s) scalars.
   */
  suspend fun signDigest(request: SignDigestRequest): DerSignatureResult
  /**
   * Requests hardware attestation for the key, embedding [request.challenge] into the certificate
   * chain to verify hardware backing.
   */
  suspend fun attestKey(request: AttestationRequest): AttestationResult
  /** Retrieves the public key coordinates for an existing keypair by [keyAlias]. */
  fun getPublicKey(keyAlias: String): EnclavePublicKey
  /** Checks if a keypair exists for the specified [keyAlias]. */
  fun hasKey(keyAlias: String): Boolean
  /** Deletes the keypair identified by [keyAlias] from the hardware keystore. */
  fun deleteKey(keyAlias: String): Boolean

  companion object {
    /** The codec used by HardwareKeyHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      KeyApiPigeonCodec()
    }
    /** Sets up an instance of `HardwareKeyHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HardwareKeyHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.isHardwareIsolationSupported$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val levelArg = args[0] as EnclaveIsolationLevel
            val wrapped: List<Any?> = try {
              listOf(api.isHardwareIsolationSupported(levelArg))
            } catch (exception: Throwable) {
              KeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.generateKeyPair$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as KeyGenerationRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.generateKeyPair(requestArg))
              } catch (exception: Throwable) {
                KeyApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.signDigest$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SignDigestRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.signDigest(requestArg))
              } catch (exception: Throwable) {
                KeyApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.attestKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as AttestationRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.attestKey(requestArg))
              } catch (exception: Throwable) {
                KeyApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.getPublicKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.getPublicKey(keyAliasArg))
            } catch (exception: Throwable) {
              KeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.hasKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.hasKey(keyAliasArg))
            } catch (exception: Throwable) {
              KeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.chainkey_platform_interface.HardwareKeyHostApi.deleteKey$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyAliasArg = args[0] as String
            val wrapped: List<Any?> = try {
              listOf(api.deleteKey(keyAliasArg))
            } catch (exception: Throwable) {
              KeyApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
